language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "started"

script:
  - docker --version # print the version for logging  
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed tungpl/udagram-api-feed:v1.6
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user tungpl/udagram-api-user:v1.6
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend tungpl/udagram-frontend:v1.6
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy tungpl/reverseproxy:v1.6

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
  - docker push tungpl/udagram-api-feed:v1.6
  - docker push tungpl/udagram-api-user:v1.6
  - docker push tungpl/udagram-frontend:v1.6
  - docker push tungpl/reverseproxy:v1.6

