apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: "tungpl/reverseproxy:v2"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-configmap
